/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uxtidvqvtgmysnxupqda"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dGlkdnF2dGdteXNueHVwcWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzgyMTIsImV4cCI6MjA3MzQxNDIxMn0.d9KwYd8PIUbZTTtKEzVyHlhEJb_4jfEJ4-ISfx-waqY"